model_name: "flux-dev"
data_config:
  num_workers: 4
  img_size: 512
  img_dir: top_478k_no_crop_no_sketch_021223
  #img_dir: mj_3.1k_jpg
  image_column: "image"
  caption_column: "text"

report_to: tensorboard
train_batch_size: 4
output_dir: ckpt_sketch/
max_train_steps: 100000
learning_rate: 2e-5
lr_scheduler: constant
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 1000
checkpoints_total_limit: 10
tracker_project_name: sketch
resume_from_checkpoint: latest
gradient_accumulation_steps: 2
